educonnect/parents/forms.py
#!/usr/bin/python3
"""Forms for the students module"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, FileField, IntegerField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

educonnect/admins/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from educonnect import bcrypt
from educonnect.models.admin_model import Admin
from educonnect.models.teacher import Teacher
from educonnect.models.school import School
from educonnect.models.classroom import Classroom
from educonnect.admins.forms import RegistrationForm, DeleteForm, RegisterClassroomForm, DeleteClassroomForm
from educonnect import db_storage
from flask_pagination   import Pagination
from flask_paginate import get_page_args



admins = Blueprint('admins', __name__)

#function for the admin home page
@admins.route('/admin', methods=['POST', 'GET'], strict_slashes=False)
def admin():
    """admin route"""
    return render_template('admin.html')

#create route for deleting a classroom
@admins.route('/delete_classroom', methods=['POST', 'GET'], strict_slashes=False)
def delete_classroom():
    """delete classroom route"""
    form = DeleteClassroomForm()
    if form.validate_on_submit():
        classroom = db_storage.all(Classroom).values()
        for c in classroom:
            if c.name == form.name.data:
                db_storage.delete(c)
                db_storage.save()
                flash(f'Classroom deleted for {form.name.data}!', 'success')
                return redirect(url_for('admins.admin'))
    return render_template('delete_classroom.html', title='Delete Classroom', form=form)


#route for registering a classroom to a school, check if the school_id is present in the database
@admins.route('/register_classroom', methods=['POST', 'GET'], strict_slashes=False)
def register_classroom():
    """register classroom route"""
    form = RegisterClassroomForm()
    if form.validate_on_submit():
        school = db_storage.get(School, form.school_id.data)
        if school:
            classroom = Classroom(name=form.name.data, school=school)
            db_storage.new(classroom)
            db_storage.save()
            flash(f'Classroom created for {form.name.data}!', 'success')
            return redirect(url_for('admins.admin'))
        else:
            flash(f'School ID not found', 'danger')
    return render_template('register_classroom.html', title='Register Classroom', form=form)

#create a route that allows the user to delete a teacher from the database, use the delete method from the storage class to delete the teacher
@admins.route('/delete_teacher', methods=['POST', 'GET'], strict_slashes=False)
def delete_teacher():
    """delete route"""
    form = DeleteForm()
    if form.validate_on_submit():
        teacher = db_storage.all('Teacher')
        for t in teacher:
            if t.email == form.email.data:
                db_storage.delete(t)
                db_storage.save()
                flash(f'Account deleted for {form.email.data}!', 'success')
                return redirect(url_for('main.login'))
    return render_template('delete_teacher.html', title='Delete Teacher', form=form)

#create a route that registers a teacher to a school, check if the school_id is present in the database
@admins.route('/register_teacher', methods=['POST', 'GET'], strict_slashes=False)
def register_teacher():
    """register teacher"""
    if current_user.is_authenticated:
        return redirect(url_for('teachers.teacher'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        school = db_storage.get(School, form.school_id.data)
        if school:
            teacher = Teacher(email=form.email.data, password=hashed_password, first_name=form.first_name.data, last_name=form.last_name.data, school=school)
            db_storage.new(teacher)
            db_storage.save()
            flash(f'Account created for {form.email.data}!', 'success')
            return redirect(url_for('main.login'))
        else:
            flash(f'School ID not found', 'danger')
    return render_template('register_teacher.html', title='Register Teacher', form=form)

educonnect/main/routes.py
#!/usr/bin/python3
"""Routes for the main module"""

from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask_login import login_user, current_user, logout_user, login_required
from educonnect import bcrypt
from educonnect.models.admin_model import Admin
from educonnect.models.teacher import Teacher
from educonnect.models.student import Student
from educonnect.models.parent import Parent
from educonnect.models.school import School
from educonnect.models.classroom import Classroom
from educonnect.models.assignment import Assignment
from educonnect.main.forms import RegistrationForm, LoginForm, UpdateAccountForm
from educonnect import db_storage
from educonnect.main.utils import save_picture
from flask_paginate import Pagination, get_page_args


main = Blueprint('main', __name__)

@main.route('/login', methods=['POST', 'GET'], strict_slashes=False)
def login():
    """login route"""
    form = LoginForm()
    if form.validate_on_submit():
        user_data = {}
        for model_class in [Admin, Teacher, Student, Parent, School]:
            user_data.update(db_storage.all(model_class))
        for user in user_data.values():
            if user.email == form.email.data and bcrypt.check_password_hash(user.password, form.password.data):
                session['email'] = form.email.data
                session['password'] = form.password.data
                login_user(user, remember=form.remember.data)
                
                if isinstance(user, Admin):
                    return redirect(url_for('admins.admin'))
                elif isinstance(user, Teacher):
                    return redirect(url_for('teachers.teacher'))
                elif isinstance(user, Student):
                    return redirect(url_for('student.student'))
                elif isinstance(user, Parent):
                    return redirect(url_for('parents.parent'))
                elif isinstance(user, School):
                    session['school_id'] = user.id
                    return redirect(url_for('school.school'))
        flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


#function for home route
@main.route('/')
@main.route('/home', methods=['POST', 'GET'], strict_slashes=False)
def home():
    """home route"""
    return render_template('home.html')

#function for about route
@main.route('/about', methods=['POST', 'GET'], strict_slashes=False)
def about():
    """about route"""
    return render_template('about.html')

#function for contact route
@main.route('/contact', methods=['POST', 'GET'], strict_slashes=False)
def contact():
    """contact route"""
    return render_template('contact.html')

#a route for general registration of a parent or student
@main.route('/register', methods=['POST', 'GET'], strict_slashes=False)
def register():
    """register route"""
    return render_template('registrationpage.html')


@main.route('/account', methods=['POST', 'GET'], strict_slashes=False)
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.email = form.email.data
        db_storage.save()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('main.account'))
    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

#function for the logout route
@main.route('/logout', methods=['POST', 'GET'], strict_slashes=False)
@login_required
def logout():
    """logout route"""
    logout_user()
    session.clear()
    return redirect(url_for('main.home'))

#create route for view_classsroom and use paginate to display the data
@main.route('/view_classroom', methods=['POST', 'GET'], strict_slashes=False)
def view_classroom():
    """view classroom route"""
    classroom_data = db_storage.all(Classroom)
    classrooms = list(classroom_data.values())
    return render_template('view_classroom.html', title='View Classroom', classrooms=classrooms)

#create a route that allows the user to view the assignments that have been posted, query the database without using the all method
@main.route('/view_assignment', methods=['POST', 'GET'], strict_slashes=False)
def view_assignment():
    """view assignment route"""
    assignment_data = db_storage.all(Assignment)
    assignments = list(assignment_data.values())
    return render_template('view_assignment.html', title='View Assignment', assignments=assignments)

#route for viewings the students
@main.route('/view_student', methods=['POST', 'GET'], strict_slashes=False)
def view_student():
    """view student route"""
    
    student_data = db_storage.all(Student)
    students = list(student_data.values())
    print(students)
    return render_template('view_student.html', title='View Student', students=students)

#create route for registration of a parent to a school, check if the school_id is present in the database
@main.route('/register_parent', methods=['POST', 'GET'], strict_slashes=False)
def register_parent():
    """register parent"""
    if current_user.is_authenticated:
        return redirect(url_for('parents.parent'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        school = db_storage.get(School, form.school_id.data)
        if school:
            parent = Parent(email=form.email.data, password=hashed_password, first_name=form.first_name.data, last_name=form.last_name.data, school=school)
            db_storage.new(parent)
            db_storage.save()
            flash(f'Account created for {form.email.data}!', 'success')
            return redirect(url_for('main.login'))
        else:
            flash(f'School ID not found', 'danger')
    return render_template('register_parent.html', title='Register Parent', form=form)

#create a route for registering a student to a school, check if the school_id is present in the database
@main.route('/register_student', methods=['POST', 'GET'], strict_slashes=False)
def register_student():
    """register student"""
    if current_user.is_authenticated:
        return redirect(url_for('students.student'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        school = db_storage.get(School, form.school_id.data)
        if school:
            student = Student(email=form.email.data, password=hashed_password, first_name=form.first_name.data, last_name=form.last_name.data, school=school)
            db_storage.new(student)
            db_storage.save()
            flash(f'Account created for {form.email.data}!', 'success')
            return redirect(url_for('main.login'))
        else:
            flash(f'School ID not found', 'danger')
    return render_template('register_student.html', title='Register Student', form=form)

#create a route for viewing all the teachers and paginate it
@main.route('/view_teacher', methods=['POST', 'GET'], strict_slashes=False)
def view_teacher():
    """view teachers paginated route"""
    page, per_page, offset = get_page_args(page_parameter='page', per_page_parameter='per_page')
    teachers_data = db_storage.all(Teacher)
    teachers = list(teachers_data.values())
    pagination = Pagination(page=page, per_page=per_page, total=len(teachers), css_framework='bootstrap4')
    return render_template('view_teacher.html', title='View Teacher', teachers=teachers[offset: offset + per_page], page=page, per_page=per_page, pagination=pagination)

educonnect/parents/routes.py
#!/bin/usr/python3
"""Routes for the parents module"""

from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask_login import login_user, current_user, logout_user, login_required
from educonnect.models.parent import Parent
from educonnect import db_storage

parents = Blueprint('parents', __name__)

#a function for the parents homepage
@parents.route('/parent', methods=['POST', 'GET'], strict_slashes=False)
def parent():
    """parent route"""
    return render_template('parent.html')

educonnect/school/routes.py
#!/usr/bin/python3
"""Routes for the school module"""

from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask_login import login_user, current_user, logout_user, login_required
from educonnect import bcrypt
from educonnect.models.school import School
from educonnect.models.admin_model import Admin
from educonnect.school.forms import RegisterSchoolForm, RegisterAdminForm
from educonnect import db_storage
import logging

school_blueprint = Blueprint('school', __name__)

#function for the school homepage
@school_blueprint.route('/school', methods=['POST', 'GET'], strict_slashes=False)
def school():
    """school route"""
    if 'school_id' in session:
        school_id = session['school_id']
        school = db_storage.get(School, school_id)

        if school:
            school_name = school.name
            return render_template('school.html', school_name=school_name, school_id=school_id)
        else:
            logging.error(f"School not found with ID: {school_id}")
            return render_template('error.html', message="School not found"), 404
    else:
        logging.error("Error number 2, school ID not found in session")
        return render_template('error.html', message="School ID not found in session"), 404

#function to register a school
@school_blueprint.route('/register_school', methods=['POST', 'GET'], strict_slashes=False)
def register_school():
    """register route"""
    form = RegisterSchoolForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        school = School(email=form.email.data, password=hashed_password, name=form.name.data, address=form.address.data, county=form.county.data, phone=form.phone.data, website=form.website.data)
        db_storage.new(school)
        db_storage.save()
        flash(f'Account created for {form.name.data}!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register_school.html', title='Register Your School', form=form)


@school_blueprint.route('/register_admin', methods=['POST', 'GET'], strict_slashes=False)
@login_required
def register_admin():
    """Register admin"""
    if isinstance(current_user, School):
        form = RegisterAdminForm()
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            school = current_user  # Use the current logged-in school
            admin = Admin(email=form.email.data, password=hashed_password, first_name=form.first_name.data, last_name=form.last_name.data, school=school)
            db_storage.new(admin)
            db_storage.save()
            flash(f'Account created for {form.email.data}!', 'success')
            return redirect(url_for('school.school'))
        return render_template('register_admin.html', title='Register Admin', form=form)
    else:
        flash('Only schools can register admins', 'danger')
        return redirect(url_for('main.login'))

educonnect/students/routes.py
#!/usr/bin/python3
"""Routes for the students module"""

from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask_login import login_user, current_user, logout_user, login_required
from educonnect.models.assignment import Assignment

from educonnect.students.forms import SubmitAssignmentForm
from educonnect import db_storage


students = Blueprint('students', __name__)

#function for the students home page
@students.route('/student', methods=['POST', 'GET'], strict_slashes=False)
def student():
    """student route"""
    return render_template('student.html')

#route for submitting assignments, check if the assignment_id is present in the database
@students.route('/submit_assignment', methods=['POST', 'GET'], strict_slashes=False)
def submit_assignment():
    """submit assignment route"""
    form = SubmitAssignmentForm()
    if form.validate_on_submit():
        assignment = db_storage.get(Assignment, form.assignment_id.data)
        if assignment:
            assignment.student_id = form.student_id.data
            assignment.submission = form.submission.data
            db_storage.save()
            flash(f'Assignment submitted for {form.assignment_id.data}!', 'success')
            return redirect(url_for('students.student'))
        else:
            flash(f'Assignment ID not found', 'danger')
    return render_template('submit_assignment.html', title='Submit Assignment', form=form)

educonnect/templates/about.html
{% extends 'layout.html'%}
{% block title%} About Us {% endblock %}
{% block content%}

<h1>About Us</h1>
    
<h2>Inspiration Behind the Project:</h2>

<p>Our journey towards building this platform began with a simple realization that the traditional methods of communication and collaboration in educational settings were ripe for innovation. As former students ourselves, we vividly recall the challenges of staying organized amidst a deluge of assignments, the frustration of missing crucial announcements, and the disconnect between school and home.<p>

<p>During our research, we also considered the challenges that parents go through following up with their children's performance and progress, and also the ease of teachers issuing assignments and deadlines. This also brought the issue of parents' ability to communicate with specific course teachers and vice versa, and including accessibility made so much sense.<p>

<p>Driven by a passion for transforming these challenges into opportunities, we embarked on this project with a shared vision to create a digital ecosystem that seamlessly connects parents, teachers and students, empowering them to communicate effectively, collaborate effortlessly, and succeed academically.</p>

<h2>Timeline and Purpose:</h2>

<p>Over the course of one and a half months, we poured our hearts and minds into this endeavor, meticulously designing and developing each feature with the user experience at the forefront. What began as a spark of inspiration evolved into a full-fledged project, culminating in the creation of this platform.</p>

<p>This project is not merely an academic exercise; it is a testament to our dedication, creativity, and perseverance. As Portfolio Project participants at Holberton School, we are proud to present this platform as a showcase of our skills and a reflection of our commitment to excellence in software development.<p>

</div>
<div class="col-md-4">
    <a href="https://holbertonschool.com/" target="_blank">Portfolio Project for Holberton School</a>
</div>



<h2>Team Members</h2>
<ul>
    <li>Elizabeth Gatura</li>
    <li>Blair Muhindi</li>
</ul>

<ul>
    <li><a href="https://www.linkedin.com/in/elizabeth-gatura">Elizabeth Gatura (LinkedIn)</a></li>
    <li><a href="https://github.com/Mutahe">Elizabeth Gatura (GitHub)</a></li>
    <li><a href="https://x.com/Lizgatura?t=IeJ00yHXlVyFusn31omjng&s=09">Elizabeth Gatura (Twitter)</a></li>

    <li><a href="https://www.linkedin.com/in/blairmuhindi">Blair Muhindi (LinkedIn)</a></li>
    <li><a href="https://github.com/Isiji">Blair Muhindi (GitHub)</a></li>
    <li><a href="https://x.com/basterblair?t=9W7iu8Zh3zyhYfO1dojPsA&s=08">Blair Muhindi (Twitter)</a></li>

**GitHub Repository:**

<li><a href="https://github.com/Isiji/EduConnect_System">EduConnect System</a></li>

{% endblock %}

educonnect/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{url_for('static', filename = 'images/profile.jpeg') }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.first_name.label(class="form-control-label") }}

                    {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.first_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.last_name.label(class="form-control-label") }}

                    {% if form.last_name.errors %}
                        {{ form.lasst_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.lasst_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.last_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

educonnect/templates/admin.html
{%extends 'layout.html'%}
{%block title%} Admin Panel {%endblock%}
{%block content%}
<div class="container">
    <h1>Admin Panel</h1>
    <p>Welcome to the admin panel, {{session['username']}}</p>
    <p>Here you can manage the users and the posts</p>
    <div class="row">
        <div class="col-md-4">
            <a href="{{url_for('admins.register_teacher')}}" class="btn btn-primary">Register Teacher</a>
        </div>
        <div class="col-md-4">
            <a href="{{url_for('admins.register_classroom')}}" class="btn btn-primary">Register Classroom</a>
        </div>
        <div class="col-md-4">
            <a href="{{url_for('main.register_student')}}" class="btn btn-primary">Register Student</a>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-4">
            <a href="{{url_for('school.register_admin')}}" class="btn btn-primary">Register Admin</a><br>

        </div>
        <div class="col-md-4">
            <a href="{{url_for('admins.delete_teacher')}}" class="btn btn-danger">Delete Teacher</a>

        </div>
        <div class="col-md-4">
            <a href="{{url_for('main.logout')}}" class="btn btn-danger">Logout</a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-4">
            <a href="{{url_for('main.view_teacher')}}" class="btn btn-primary">view Teacher</a>
        </div>
        <div class="col-md-4">
            <a href="{{url_for('admins.delete_classroom')}}" class="btn btn-primary">Delete Classroom</a>
        </div>
        <div class="col-md-4">
            <a href="{{url_for('main.account')}}" class="btn btn-primary">Account</a>
        </div>
    </div>
</div>
{%endblock%}

educonnect/templates/delete_assignment.html
{%extends 'layout.html'%}
{%block title%} Delete Assignment {%endblock%}
{%block content%}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Assignment</legend>
                <div class="form-group">
                    {{ form.assignment_id.label(class="form-control-label") }}

                    {% if form.assignment_id.errors %}
                        {{ form.assignment_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.assignment_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.assignment_id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Delete Assignment</button>
                </div>
            </fieldset>
        </form>
    </div>
{%endblock%}

educonnect/templates/delete_classroom.html
{%extends 'layout.html'%}
{%block title%} Delete Classroom {%endblock%}
{%block content%}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Classroom</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}

                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Delete Classroom</button>
                </div>
            </fieldset>
        </form>
    </div>
{%endblock%}

educonnect/templates/error.html
{%extends 'layout.html'%}
{%block title%} Error {%endblock%}
{%block content%}
    <div class="container">
        <h1>Error</h1>
        <p>There was an error processing your request</p>
        <a href="{{url_for('main.home')}}" class="btn btn-primary">Home</a>
    </div>
{%endblock%}

educonnect/templates/login.html
{% extends 'layout.html' %}
{% block title %} Log In {% endblock %}
{% block content %}


    <div class="content-section">
        <form method="POST" action=" {{ url_for('main.login')}}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('school.register_school') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

educonnect/templates/student.html
{%extends 'layout.html'%}
{%block title%} Student Panel {%endblock%}
{%block content%}
<div class="container">
    <h1>Student Panel</h1>
    <p>Welcome to the student panel, {{session['username']}}</p>
    <p>Here you can view the assignments</p>
    <div class="row">
        <div class="col-md-4">
            <a href="{{url_for('main.view_assignment')}}" class="btn btn-primary">View Assignment</a>
        </div>
        <div class="col-md-4">
            <a href="{{url_for('students.submit_assignment')}}" class="btn btn-success">Submit Assignment</a>
        </div>
        <div class="col-md-4">
            <a href="{{url_for('main.logout')}}" class="btn btn-danger">Logout</a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-4">
            <a href="{{url_for('main.account')}}" class="btn btn-primary">Account</a>
        </div>
</div>
{%endblock%}